{
 "title": "Call Flow",
 "tags": [ "homer" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "method",
    "label": "method",
    "query": {}
   },
   {
    "name": "src_ip",
    "label": "Source IP",
    "query": {}
   },
   {
    "name": "dst_ip",
    "label": "Dest. IP",
    "query": {}
   },
   { "name": "search", "label": "Full-Text Regex Search" }
  ]
 },
 "panels": [
  { "title": "HOMER 10", "type": "canvas", "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 } },
  {
   "title": "HEP Flow",
   "type": "qxip-flow-panel",
   "gridPos": { "h": 17, "w": 18, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "{job=\"heplify-server\", src_ip=~\"$src_ip\", dst_ip=~\"$dst_ip\"} | response=~\"$method\" or type!=\"sip\" |~ `$search`",
     "maxLines": 100
    }
   ]
  },
  {
   "title": "Histogram",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (type, response) (count_over_time({job=\"heplify-server\", response=~\"$method\", src_ip=~\"$src_ip\", dst_ip=~\"$dst_ip\"} |~ `$search` [$__interval]))\n"
    }
   ]
  },
  {
   "title": "Method Distribution",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (type, response) (count_over_time({job=\"heplify-server\", response=~\"$method\", src_ip=~\"$src_ip\", dst_ip=~\"$dst_ip\"} |~ `${search:raw}` [$__interval]))\n"
    }
   ]
  }
 ]
}