#                                    __   __  __
#                                    \ \ / / / /
#                                     \ V / / /
#                                      \_/  \/
#
#                                    V E C T O R
#                                   Configuration
#
# ------------------------------------------------------------------------------
# Website: https://vector.dev
# Docs: https://vector.dev/docs
# Chat: https://chat.vector.dev
# ------------------------------------------------------------------------------

# Change this to use a non-default directory for Vector data storage:
# data_dir = "/var/lib/vector"

[sources.my_journald_source]
type = "journald"

[sinks.qryn]
type = "loki"
inputs = ["my_journald_source"]
endpoint = "${QRYN_SERVER}"
compression = "none"
out_of_order_action = "accept"

[sinks.qryn.auth]
strategy="basic"
user="${QRYN_USER}"
password="${QRYN_PASSWORD}"

[sinks.qryn.labels]
forwarder = "vector"
event = "{{ SYSLOG_IDENTIFIER }}"
type = "syslog"

[sinks.qryn.encoding]
codec = "json"

# Vector's GraphQL API (disabled by default)
# Uncomment to try it out with the `vector top` command or
# in your browser at http://localhost:8686
#[api]
#enabled = true
#address = "127.0.0.1:8686"

[sources.homer_scrape]
type = "prometheus_scrape"
endpoints = [ "http://localhost:9096/metrics" ]
scrape_interval_secs = 10
instance_tag = "heplify"
endpoint_tag = "homer"

[sinks.prom_write]
type = "prometheus_remote_write"
inputs = [ "homer_scrape" ]
endpoint = "${QRYN_SERVER}/api/prom/remote/write"

[sinks.prom_write.auth]
strategy="basic"
user="${QRYN_USER}"
password="${QRYN_PASSWORD}"
